package io.github.headmaster218.recorder.core;

import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/** Synthetic host checks; no Android API or device execution. Keeps every generated fixture. */
public final class CaptureAnchorsTest {
    private static final String DOMAIN = "11111111-1111-1111-1111-111111111111";
    private static final String OTHER_DOMAIN = "22222222-2222-2222-2222-222222222222";
    private static final String HASH = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
    private static int checks, number;
    private static final Path BASE = Paths.get("app/build/capture-anchor-tests/fixtures/run-"+System.nanoTime());
    private interface Action { void run() throws Exception; }
    private static void yes(boolean ok) { checks++; if (!ok) throw new AssertionError("anchor check "+checks); }
    private static void fails(Action action) throws Exception { checks++; try { action.run(); } catch (IOException | IllegalArgumentException | IllegalStateException expected) { return; } throw new AssertionError("expected rejection "+checks); }
    private static Path root() throws IOException { return Files.createDirectories(BASE.resolve("case-"+number++)); }
    private static CaptureTimeline.Epoch epoch(int channels,long n,String run) { return new CaptureTimeline.Epoch("capture",run,n,new PcmFormat(16000,channels),"phone","route",n==0 ? CaptureTimeline.Gap.START : CaptureTimeline.Gap.ROUTE_CHANGE_UNCERTAIN); }
    private static DirectorySpool spool(Path root) throws IOException { return new DirectorySpool(root,new CachePolicy(1000000,0),new DirectorySpool.NioProtocol(),(op,path)->{}); }
    private static CaptureAnchors.Timestamp available(long frame,long nanos) { return new CaptureAnchors.Timestamp(CaptureAnchors.TimestampStatus.AVAILABLE,0,frame,nanos,nanos+1,nanos+2); }
    private static CaptureAnchors.Read read(long ordinal,long before,long count,CaptureAnchors.Timestamp t,int flags) {
        long ns = 1000000000L + ordinal*1000000000L;
        return new CaptureAnchors.Read(DOMAIN,"run",ordinal,before,before+count,ns,ns+100,ns+101,1700000000000L+ordinal*1000,ns+102,1000+ordinal*1000,0,0,t,flags);
    }
    private static byte[] unhex(String value) { byte[] b = new byte[value.length()/2]; for (int i=0;i<b.length;i++) b[i]=(byte)Integer.parseInt(value.substring(i*2,i*2+2),16); return b; }
    private static byte[] reseal(byte[] payload) { byte[] b=Arrays.copyOf(payload,payload.length+32); System.arraycopy(PcmSegmentWriter.sha256().digest(payload),0,b,payload.length,32); return b; }
    private static void legacyGoldens() throws Exception {
        // Generated by the unmodified 60767916 core, independently compiled before these tests.
        byte[] intent = unhex("50434d3100000001000763617074757265000372756e000000000000000000003e8000000002000570686f6e650005726f75746500055354415254000000000000000300000000000000000000000000000004c4cae2ec1779d2f1845238ef17eaec02e5afbd91d063053c276c1111ece66a25");
        byte[] manifest = unhex("50434d3100000001000763617074757265000372756e000000000000000000003e8000000002000570686f6e650005726f7574650005535441525400000000000000030000000000000000000000000000000400000000000000040040303132333435363738396162636465663031323334353637383961626364656630313233343536373839616263646566303132333435363738396162636465660040303132333435363738396162636465663031323334353637383961626364656630313233343536373839616263646566303132333435363738396162636465660008524f544154494f4e0036f61b728ffbe929cc6ee75832672d88164eee3f3f63fd6492e7bf54943fd27e");
        yes(Arrays.equals(intent,SegmentMetadata.encodeIntent(SegmentMetadata.decodeIntent(intent))));
        SegmentMetadata m = SegmentMetadata.decode(manifest);
        yes(m.schemaVersion==1 && m.captureAnchors==null); yes(Arrays.equals(manifest,m.encode()));
        // RFT1 envelope is byte framing around unchanged local manifest bytes.
        ByteArrayOutputStream expected = new ByteArrayOutputStream(); DataOutputStream d = new DataOutputStream(expected);
        d.writeInt(0x52465431); d.writeUTF("profile"); d.writeUTF("id"); d.writeInt(manifest.length); d.write(manifest); d.flush();
        ByteArrayOutputStream actual = new ByteArrayOutputStream(); d = new DataOutputStream(actual);
        d.writeInt(0x52465431); d.writeUTF("profile"); d.writeUTF("id"); byte[] reencoded=m.encode(); d.writeInt(reencoded.length); d.write(reencoded); d.flush();
        yes(Arrays.equals(expected.toByteArray(),actual.toByteArray()));
        yes(Arrays.equals(PcmSegmentWriter.sha256().digest(expected.toByteArray()),PcmSegmentWriter.sha256().digest(actual.toByteArray())));
    }
    private static List<SegmentStore.Published> write(Path root,int channels,long target,byte[] pcm,CaptureAnchors.Read observation) throws Exception {
        List<SegmentStore.Published> result = new ArrayList<SegmentStore.Published>();
        try (DirectorySpool spool=spool(root)) {
            PcmSegmentWriter writer = new PcmSegmentWriter(spool,epoch(channels,0,"run"),target,0,result::add);
            writer.append(pcm,0,pcm.length,observation); writer.stop();
        }
        return result;
    }
    private static void splitAndTransport() throws Exception {
        byte[] pcm = new byte[40]; for (int i=0;i<pcm.length;i++) pcm[i]=(byte)(i*17);
        CaptureAnchors.Read r=read(0,0,20,available((1L<<32)+123,1000000000L),CaptureAnchors.RUN_START);
        java.util.concurrent.ArrayBlockingQueue<CaptureAnchors.Read> queue = new java.util.concurrent.ArrayBlockingQueue<CaptureAnchors.Read>(1);
        queue.add(r); Thread.sleep(20); yes(queue.take()==r); // Synthetic consumer delay, not Android queue-pressure acceptance.
        Path observed=root(), plain=root();
        List<SegmentStore.Published> result=write(observed,2,3,pcm,r), old=write(plain,2,3,pcm,null);
        yes(result.size()==4 && old.size()==4);
        ByteArrayOutputStream assembled=new ByteArrayOutputStream();
        for (int i=0;i<result.size();i++) {
            SegmentMetadata m=result.get(i).metadata; CaptureAnchors a=m.captureAnchors;
            yes(m.schemaVersion==2 && a.firstRead==r && a.lastRead==r);
            yes(a.runSampleStart==i*6 && a.runSampleEnd==Math.min((i+1)*6,20));
            yes(a.readCount==1 && a.queryCount==1 && a.unavailableCount==0);
            yes(a.firstAvailableRead==r && a.lastAvailableRead==r);
            byte[] encoded=m.encode(); yes(encoded.length<SegmentMetadata.MAX_BYTES);
            SegmentMetadata decoded=SegmentMetadata.decode(encoded); yes(Arrays.equals(encoded,decoded.encode()));
            yes(decoded.captureAnchors.firstRead.timestamp.framePosition==(1L<<32)+123);
            yes(Arrays.equals(SegmentMetadata.encodeIntent(m.intent),SegmentMetadata.encodeIntent(old.get(i).metadata.intent)));
            byte[] wav=Files.readAllBytes(observed.resolve(result.get(i).localObjectId).resolve("audio.wav"));
            yes(Arrays.equals(wav,Files.readAllBytes(plain.resolve(old.get(i).localObjectId).resolve("audio.wav"))));
            assembled.write(wav,44,wav.length-44);
            try (java.util.stream.Stream<Path> files=Files.list(observed.resolve(result.get(i).localObjectId))) { yes(files.count()==3); }
        }
        yes(Arrays.equals(pcm,assembled.toByteArray()));
        CommittedSegments catalog=new CommittedSegments(observed); CommittedSegments.Page page=catalog.page(null);
        yes(page.entries.size()==4 && page.rejected==0);
        Method transport=FtpsTransfer.class.getDeclaredMethod("metadata",CommittedSegments.Entry.class,String.class); transport.setAccessible(true);
        byte[] envelope=(byte[])transport.invoke(null,page.entries.get(0),"profile");
        java.io.DataInputStream in=new java.io.DataInputStream(new java.io.ByteArrayInputStream(envelope));
        yes(in.readInt()==0x52465431); yes(in.readUTF().equals("profile")); yes(in.readUTF().equals(page.entries.get(0).id));
        byte[] local=new byte[in.readInt()]; in.readFully(local); yes(in.read()==-1); yes(SegmentMetadata.decode(local).schemaVersion==2);
        // Production transport encoding of a v1 catalog is stable across new-reader readback.
        CommittedSegments legacy=new CommittedSegments(plain); CommittedSegments.Entry entry=legacy.page(null).entries.get(0);
        byte[] first=(byte[])transport.invoke(null,entry,"profile"); byte[] again=(byte[])transport.invoke(null,new CommittedSegments(plain).page(null).entries.get(0),"profile");
        yes(Arrays.equals(first,again)); yes(Arrays.equals(PcmSegmentWriter.sha256().digest(first),PcmSegmentWriter.sha256().digest(again)));
    }
    private static void boundedUnavailableAndEpoch() throws Exception {
        Path root=root(); List<SegmentStore.Published> out=new ArrayList<SegmentStore.Published>();
        CaptureAnchors.Read first=null,last=null;
        try (DirectorySpool spool=spool(root)) {
            PcmSegmentWriter w=new PcmSegmentWriter(spool,epoch(1,0,"run"),10001,0,out::add);
            for (int i=0;i<10000;i++) {
                CaptureAnchors.Timestamp t=i%2==0 ? new CaptureAnchors.Timestamp(CaptureAnchors.TimestampStatus.UNAVAILABLE,-3,0,0,i+1,i+2) : CaptureAnchors.Timestamp.notPolled();
                CaptureAnchors.Read r=read(i,i,1,t,0); if (first==null) first=r; last=r;
                w.append(new byte[2],0,2,r);
            }
            w.beginEpoch(epoch(1,1,"run"));
            w.append(new byte[2],0,2,read(10000,10000,1,CaptureAnchors.Timestamp.notPolled(),CaptureAnchors.ROUTE_UNCERTAIN)); w.stop();
        }
        CaptureAnchors a=out.get(0).metadata.captureAnchors;
        yes(a.firstRead==first && a.lastRead==last && a.readCount==10000 && a.queryCount==5000 && a.unavailableCount==5000);
        yes(out.get(0).metadata.encode().length<1600); yes(out.get(1).metadata.intent.frameStart==0);
        yes(out.get(1).metadata.captureAnchors.runSampleStart==10000 && out.get(1).metadata.captureAnchors.flags==CaptureAnchors.ROUTE_UNCERTAIN);
        // Later serialization and writer delay preserve producer values rather than sampling a new clock.
        yes(SegmentMetadata.decode(out.get(0).metadata.encode()).captureAnchors.firstRead.readBeforeNanos==first.readBeforeNanos);
        CaptureAnchors.Collector c=new CaptureAnchors.Collector(); c.add(first,0,1);
        CaptureAnchors.Read other=new CaptureAnchors.Read(OTHER_DOMAIN,"run",1,1,2,1,2,3,4,5,6,0,0,CaptureAnchors.Timestamp.notPolled(),0);
        fails(()->c.add(other,1,2));
    }
    private static void anomalies() {
        CaptureAnchors.Observer o=new CaptureAnchors.Observer(); CaptureAnchors.Read first=read(0,0,1,available((1L<<32)+5,1000000000L),CaptureAnchors.RUN_START); o.accepted(first);
        int f=o.flags(1,2000000000L,2000000001L,2000000002L,1700000010000L,2000000003L,1000,0,1,available(7,900000000L));
        yes((f & CaptureAnchors.TIMESTAMP_REGRESSION)!=0); yes((f & CaptureAnchors.WALL_JUMP)!=0); yes((f & CaptureAnchors.ROUTE_UNCERTAIN)!=0);
        f=o.flags(1,3000000000L,3000000001L,3000000002L,1700000002000L,3000000003L,1000,0,0,available((1L<<32)+5,1000000000L));
        yes((f & CaptureAnchors.TIMESTAMP_REPEATED)!=0 && (f & CaptureAnchors.SUSPEND_UNCERTAIN)!=0);
        CaptureAnchors.Timestamp stale=new CaptureAnchors.Timestamp(CaptureAnchors.TimestampStatus.AVAILABLE,0,7,1,4000000000L,4000000001L);
        yes((o.flags(1,2,1,2,3,1,0,0,0,stale) & (CaptureAnchors.CLOCK_REGRESSION|CaptureAnchors.TIMESTAMP_STALE))==(CaptureAnchors.CLOCK_REGRESSION|CaptureAnchors.TIMESTAMP_STALE));
        yes(CaptureAnchors.MAPPING.equals("UNESTABLISHED"));
        CaptureAnchors.Observer restart=new CaptureAnchors.Observer();
        yes((restart.flags(0,1,2,3,4,5,6,0,0,available(0,1)) & CaptureAnchors.RUN_START)!=0);
    }
    private static void malformedAndPreserve() throws Exception {
        Path root=root(); byte[] pcm={1,2,3,4};
        SegmentMetadata m=write(root,1,2,pcm,read(0,0,2,CaptureAnchors.Timestamp.notPolled(),0)).get(0).metadata;
        byte[] good=m.encode(), corrupt=good.clone(); corrupt[40]^=1; fails(()->SegmentMetadata.decode(corrupt));
        fails(()->SegmentMetadata.decode(Arrays.copyOf(good,good.length-1))); fails(()->SegmentMetadata.decode(new byte[8193]));
        fails(()->SegmentMetadata.decode(reseal(Arrays.copyOf(good,good.length-31))));
        byte[] unknown=Arrays.copyOf(good,good.length-32); unknown[7]=3; fails(()->SegmentMetadata.decode(reseal(unknown)));
        fails(()->SegmentMetadata.decodeIntent(good));
        CaptureAnchors.Read exceptional=read(0,0,2,new CaptureAnchors.Timestamp(CaptureAnchors.TimestampStatus.QUERY_EXCEPTION,0,0,0,1,2),0);
        SegmentMetadata exceptionMetadata=write(root(),1,2,pcm,exceptional).get(0).metadata;
        CaptureAnchors exceptionSummary=SegmentMetadata.decode(exceptionMetadata.encode()).captureAnchors;
        yes(exceptionSummary.unavailableCount==1 && exceptionSummary.firstAvailableRead==null);
        yes(exceptionSummary.lastQueryRead.timestamp.status==CaptureAnchors.TimestampStatus.QUERY_EXCEPTION);
        Path failed=root(); List<SegmentStore.Published> out=new ArrayList<SegmentStore.Published>();
        try (DirectorySpool spool=new DirectorySpool(failed,new CachePolicy(1000000,0),new DirectorySpool.NioProtocol(),(op,path)->{ if(op==DirectorySpool.Operation.WRITE_MANIFEST) throw new IOException("injected"); })) {
            PcmSegmentWriter w=new PcmSegmentWriter(spool,epoch(1,0,"run"),2,0,out::add);
            fails(()->w.append(pcm,0,pcm.length,read(0,0,2,CaptureAnchors.Timestamp.notPolled(),0)));
        }
        yes(out.isEmpty());
        try(java.util.stream.Stream<Path> files=Files.walk(failed)) {
            Path wav=files.filter(p->p.getFileName().toString().equals("audio.wav")).findFirst().get();
            byte[] retained=Files.readAllBytes(wav); yes(Arrays.equals(pcm,Arrays.copyOfRange(retained,44,retained.length)));
            yes(wav.getParent().getFileName().toString().endsWith(".part"));
        }
    }
    private static void crossSegmentObservationIdentity() throws Exception {
        Path path=root(); List<SegmentStore.Published> out=new ArrayList<SegmentStore.Published>();
        try (DirectorySpool spool=spool(path)) {
            PcmSegmentWriter w=new PcmSegmentWriter(spool,epoch(1,0,"run"),1,0,out::add);
            CaptureAnchors.Read first=read(0,0,1,CaptureAnchors.Timestamp.notPolled(),0);
            w.append(new byte[2],0,2,first);
            fails(()->w.append(new byte[2],0,2,first));
            CaptureAnchors.Read other=new CaptureAnchors.Read(OTHER_DOMAIN,"run",1,1,2,1,2,3,4,5,6,0,0,CaptureAnchors.Timestamp.notPolled(),0);
            fails(()->w.append(new byte[2],0,2,other));
            w.append(new byte[2],0,2,read(1,1,1,CaptureAnchors.Timestamp.notPolled(),0));
            CaptureTimeline.Epoch restart=new CaptureTimeline.Epoch("capture","new-run",1,PcmFormat.DEFAULT,"phone","route",CaptureTimeline.Gap.RESTART);
            w.beginEpoch(restart);
            CaptureAnchors.Read fresh=new CaptureAnchors.Read(OTHER_DOMAIN,"new-run",0,0,1,1,2,3,4,5,6,0,0,CaptureAnchors.Timestamp.notPolled(),CaptureAnchors.RUN_START);
            w.append(new byte[2],0,2,fresh); w.stop();
        }
        yes(out.size()==3 && out.get(2).metadata.captureAnchors.firstRead.ordinal==0);
        yes(out.get(2).metadata.captureAnchors.firstRead.processClockDomain.equals(OTHER_DOMAIN));
    }
    private static void oversizedFinalization() throws Exception {
        char[] text = new char[512]; Arrays.fill(text,'\u4e00'); String wide = new String(text);
        CaptureTimeline.Epoch e = new CaptureTimeline.Epoch(wide,wide,0,PcmFormat.DEFAULT,wide,wide,CaptureTimeline.Gap.START);
        CaptureAnchors.Read r = new CaptureAnchors.Read(DOMAIN,wide,0,0,2,1,2,3,4,5,6,0,0,CaptureAnchors.Timestamp.notPolled(),0);
        CaptureTimeline t = new CaptureTimeline(e,2,0); t.appendFrames(2);
        yes(new SegmentMetadata(new SegmentMetadata.Intent(e,0,0,2),t.seal(HASH,CaptureTimeline.Close.ROTATION),HASH).encode().length < SegmentMetadata.MAX_BYTES);
        Path path = root(); List<SegmentStore.Published> out = new ArrayList<SegmentStore.Published>();
        byte[] pcm = {11,12,13,14};
        try (DirectorySpool spool = spool(path)) {
            PcmSegmentWriter writer = new PcmSegmentWriter(spool,e,2,0,out::add);
            fails(()->writer.append(pcm,0,4,r));
        }
        yes(out.isEmpty());
        try (java.util.stream.Stream<Path> files = Files.walk(path)) {
            Path wav = files.filter(p->p.getFileName().toString().equals("audio.wav")).findFirst().get();
            byte[] bytes = Files.readAllBytes(wav);
            yes(Arrays.equals(pcm,Arrays.copyOfRange(bytes,44,bytes.length)));
            yes(wav.getParent().getFileName().toString().endsWith(".part"));
            yes(!Files.exists(wav.getParent().resolve("manifest.bin")));
        }
    }
    public static void main(String[] args) throws Exception {
        legacyGoldens(); splitAndTransport(); boundedUnavailableAndEpoch(); anomalies(); malformedAndPreserve(); oversizedFinalization(); crossSegmentObservationIdentity();
        System.out.println("PASS: "+checks+" capture-anchor assertions; synthetic host observations only");
    }
}
